package APP;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import APP.excelRead;
import com.sun.deploy.panel.ExceptionListDialog;
import com.sun.xml.internal.messaging.saaj.soap.JpegDataContentHandler;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author SCIRoof
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author SCIRoof
 */
public class graphics extends JFrame {

    /**
     * Creates new form graphics
     */
    public graphics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        jMenuBar2 = new JMenuBar();
        jMenu3 = new JMenu();
        jMenu4 = new JMenu();
        jPanel = new JPanel();
        Title = new JTextField();
        jTextField1 = new JTextField();
        jComboBox1 = new JComboBox<>();
        enterButton = new JButton();
        export = new JButton();
        scrollPane = new JScrollPane();
        cboxPanel = new JPanel();
        jCheckBox1 = new JCheckBox();
        jCheckBox2 = new JCheckBox();
        jCheckBox3 = new JCheckBox();
        jCheckBox4 = new JCheckBox();
        jCheckBox6 = new JCheckBox();
        jCheckBox7 = new JCheckBox();
        jCheckBox9 = new JCheckBox();
        jCheckBox10 = new JCheckBox();
        jCheckBox11 = new JCheckBox();
        jCheckBox12 = new JCheckBox();
        jCheckBox5 = new JCheckBox();
        jCheckBox8 = new JCheckBox();
        jCheckBox13 = new JCheckBox();
        jCheckBox14 = new JCheckBox();
        jCheckBox15 = new JCheckBox();
        jCheckBox16 = new JCheckBox();
        jCheckBox17 = new JCheckBox();
        jCheckBox18 = new JCheckBox();
        jCheckBox19 = new JCheckBox();
        jCheckBox20 = new JCheckBox();
        jCheckBox21 = new JCheckBox();
        jCheckBox22 = new JCheckBox();
        jCheckBox23 = new JCheckBox();
        jCheckBox24 = new JCheckBox();
        jCheckBox25 = new JCheckBox();
        jCheckBox26 = new JCheckBox();
        jCheckBox27 = new JCheckBox();
        jCheckBox28 = new JCheckBox();
        jCheckBox29 = new JCheckBox();
        jCheckBox30 = new JCheckBox();
        jCheckBox31 = new JCheckBox();
        jCheckBox32 = new JCheckBox();
        jCheckBox33 = new JCheckBox();
        jCheckBox34 = new JCheckBox();
        jCheckBox35 = new JCheckBox();
        jCheckBox36 = new JCheckBox();
        jCheckBox37 = new JCheckBox();
        jCheckBox38 = new JCheckBox();
        jCheckBox39 = new JCheckBox();
        jCheckBox40 = new JCheckBox();
        jCheckBox41 = new JCheckBox();
        jCheckBox42 = new JCheckBox();
        jCheckBox43 = new JCheckBox();
        jCheckBox44 = new JCheckBox();
        jCheckBox45 = new JCheckBox();
        jCheckBox46 = new JCheckBox();
        jCheckBox47 = new JCheckBox();
        jCheckBox48 = new JCheckBox();
        jCheckBox49 = new JCheckBox();
        jCheckBox50 = new JCheckBox();
        jCheckBox51 = new JCheckBox();
        jCheckBox52 = new JCheckBox();
        jCheckBox53 = new JCheckBox();
        jCheckBox54 = new JCheckBox();
        jCheckBox55 = new JCheckBox();
        jCheckBox56 = new JCheckBox();
        jCheckBox57 = new JCheckBox();
        jCheckBox58 = new JCheckBox();
        jCheckBox59 = new JCheckBox();
        jCheckBox60 = new JCheckBox();
        jCheckBox61 = new JCheckBox();
        jCheckBox62 = new JCheckBox();
        jCheckBox63 = new JCheckBox();
        jCheckBox64 = new JCheckBox();
        jCheckBox65 = new JCheckBox();
        jCheckBox66 = new JCheckBox();
        jCheckBox67 = new JCheckBox();
        jCheckBox68 = new JCheckBox();
        jCheckBox69 = new JCheckBox();
        phoneNumberLabel = new JLabel();
        addressLabel = new JLabel();
        jTextField3 = new JTextField();
        jLabel4 = new JLabel();
        jTextField4 = new JTextField();
        roofTypeLabel = new JLabel();
        roofTypeBox = new JLabel();
        notesLabel = new JLabel();
        notesField = new JTextField();
        addButton = new JButton();
        Title1 = new JTextField();
        jMenuBar1 = new JMenuBar();
        jMenu2 = new JMenu();
        Exit = new JMenuItem();
        roofType = new JMenu();
        metalRoof = new JMenuItem();
        shingleRoof = new JMenuItem();
        tileRoof = new JMenuItem();
        TPO = new JMenuItem();
        polyRoof = new JMenuItem();
        builtUp = new JMenuItem();
        inputFile = new JMenuItem();
        exportFile = new JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);


        setIconImage(new ImageIcon("src/SCILogo.png").getImage());
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new Dimension(200, 200));
        setPreferredSize(new Dimension(1024, 680));
        setResizable(false);

        Title.setEditable(false);
        Title.setBackground(new Color(153, 255, 153));
        Title.setHorizontalAlignment(JTextField.CENTER);
        Title.setText("   Scope of Work Selection");
        Title.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                TitleActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{"Annual Maintenance", "Change Order", "Clean Up: All", "Coating: All", "Closing Cost", "Concrete", "Condition Report", "Contractor Spec.", "Crane Charge", "Dry-In: All ", "Engineering: All", "Exclusions: All", "Exterior Trim & Decks", "Furnish & Install", "Granules: All", "Hot Mop: All", "HVAC", "Inclusions: All", "Insulation ", "Labor: All", "LW: All", "Manufacturer's Warranty: All", "Metal Roof: All", "MISC. Services: All", "Mobilization", "Paint", "Permit Runner", "Plans and Permits: All", "Plumbing", "Pre-Job: All", "Pressure Cleaning: All ", "Repairs: All ", "Roof Flashing", "Roof Frame", "SCI Inspections: All ", "SCI Warranties: All ", "Shingle Roof: All ", "Site Work: All", "Supplied by Owner: All", "SubContractors: All ", "Tear Off: All ", "Tile Roof: All ", "Time & Material Costs", "Total Cost of Services", "Trash Removal: All", "Uniflex: All ", "Urethane: All ", "Wood Work: All "}));
        jComboBox1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        enterButton.setText("Enter");
        enterButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        export.setText("Export >> ");
        export.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        cboxPanel.addMouseWheelListener(new MouseWheelListener() {
            public void mouseWheelMoved(MouseWheelEvent evt) {
                cboxPanelMouseWheelMoved(evt);
            }
        });

        jCheckBox1.setText("null");
        jCheckBox1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("null");

        jCheckBox3.setText("null");

        jCheckBox4.setText("null");

        jCheckBox6.setText("null");

        jCheckBox7.setText("null");

        jCheckBox9.setText("null");
        jCheckBox9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("null");

        jCheckBox11.setText("null");

        jCheckBox12.setText("null");

        jCheckBox5.setText("null");
        jCheckBox5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("null");

        jCheckBox13.setText("null");

        jCheckBox14.setText("null");

        jCheckBox15.setText("null");

        jCheckBox16.setText("null");

        jCheckBox17.setText("null");
        jCheckBox17.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });

        jCheckBox18.setText("null");

        jCheckBox19.setText("null");

        jCheckBox20.setText("null");

        jCheckBox21.setText("null");
        jCheckBox21.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });

        jCheckBox22.setText("null");

        jCheckBox23.setText("null");

        jCheckBox24.setText("null");

        jCheckBox25.setText("null");

        jCheckBox26.setText("null");

        jCheckBox27.setText("null");
        jCheckBox27.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
            }
        });

        jCheckBox28.setText("null");

        jCheckBox29.setText("null");

        jCheckBox30.setText("null");

        jCheckBox31.setText("null");

        jCheckBox32.setText("null");

        jCheckBox33.setText("null");

        jCheckBox34.setText("null");

        jCheckBox35.setText("null");

        jCheckBox36.setText("null");

        jCheckBox37.setText("null");

        jCheckBox38.setText("null");

        jCheckBox39.setText("null");

        jCheckBox40.setText("null");

        jCheckBox41.setText("null");

        jCheckBox42.setText("null");


        jCheckBox43.setText("null");

        jCheckBox44.setText("null");

        jCheckBox45.setText("null");

        jCheckBox46.setText("null");


        jCheckBox47.setText("null");

        jCheckBox48.setText("null");

        jCheckBox49.setText("null");

        jCheckBox50.setText("null");

        jCheckBox51.setText("null");

        jCheckBox52.setText("null");


        jCheckBox53.setText("null");

        jCheckBox54.setText("null");

        jCheckBox55.setText("null");

        jCheckBox56.setText("null");


        jCheckBox57.setText("null");

        jCheckBox58.setText("null");

        jCheckBox59.setText("null");

        jCheckBox60.setText("null");

        jCheckBox61.setText("null");

        jCheckBox62.setText("null");


        jCheckBox63.setText("null");

        jCheckBox64.setText("null");

        jCheckBox65.setText("null");

        jCheckBox66.setText("null");

        jCheckBox67.setText("null");

        jCheckBox68.setText("null");

        jCheckBox69.setText("null");

        chbox.add(jCheckBox1);
        chbox.add(jCheckBox2);
        chbox.add(jCheckBox3);
        chbox.add(jCheckBox4);
        chbox.add(jCheckBox5);
        chbox.add(jCheckBox6);
        chbox.add(jCheckBox7);
        chbox.add(jCheckBox8);
        chbox.add(jCheckBox9);
        chbox.add(jCheckBox10);
        chbox.add(jCheckBox11);
        chbox.add(jCheckBox12);
        chbox.add(jCheckBox13);
        chbox.add(jCheckBox14);
        chbox.add(jCheckBox15);
        chbox.add(jCheckBox16);
        chbox.add(jCheckBox17);
        chbox.add(jCheckBox18);
        chbox.add(jCheckBox19);
        chbox.add(jCheckBox20);
        chbox.add(jCheckBox21);
        chbox.add(jCheckBox22);
        chbox.add(jCheckBox23);
        chbox.add(jCheckBox24);
        chbox.add(jCheckBox25);
        chbox.add(jCheckBox26);
        chbox.add(jCheckBox27);
        chbox.add(jCheckBox28);
        chbox.add(jCheckBox29);
        chbox.add(jCheckBox30);
        chbox.add(jCheckBox31);
        chbox.add(jCheckBox32);
        chbox.add(jCheckBox33);
        chbox.add(jCheckBox34);
        chbox.add(jCheckBox35);
        chbox.add(jCheckBox36);
        chbox.add(jCheckBox37);
        chbox.add(jCheckBox38);
        chbox.add(jCheckBox39);
        chbox.add(jCheckBox40);
        chbox.add(jCheckBox41);
        chbox.add(jCheckBox42);
        chbox.add(jCheckBox43);
        chbox.add(jCheckBox44);
        chbox.add(jCheckBox45);
        chbox.add(jCheckBox46);
        chbox.add(jCheckBox47);
        chbox.add(jCheckBox48);
        chbox.add(jCheckBox49);
        chbox.add(jCheckBox50);
        chbox.add(jCheckBox51);
        chbox.add(jCheckBox52);
        chbox.add(jCheckBox53);
        chbox.add(jCheckBox54);
        chbox.add(jCheckBox55);
        chbox.add(jCheckBox56);
        chbox.add(jCheckBox57);
        chbox.add(jCheckBox58);
        chbox.add(jCheckBox59);
        chbox.add(jCheckBox60);
        chbox.add(jCheckBox61);
        chbox.add(jCheckBox62);
        chbox.add(jCheckBox63);
        chbox.add(jCheckBox64);
        chbox.add(jCheckBox65);
        chbox.add(jCheckBox66);
        chbox.add(jCheckBox67);
        chbox.add(jCheckBox68);
        chbox.add(jCheckBox69);


        for (int i = 0; i < chbox.size(); i++) {
            chbox.get(i).setVisible(false);
        }


        GroupLayout cboxPanelLayout = new GroupLayout(cboxPanel);
        cboxPanel.setLayout(cboxPanelLayout);
        cboxPanelLayout.setHorizontalGroup(
                cboxPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(cboxPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(cboxPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox3)
                                        .addComponent(jCheckBox4)
                                        .addComponent(jCheckBox1)
                                        .addComponent(jCheckBox2)
                                        .addComponent(jCheckBox11)
                                        .addComponent(jCheckBox12)
                                        .addComponent(jCheckBox9)
                                        .addComponent(jCheckBox10)
                                        .addComponent(jCheckBox6)
                                        .addComponent(jCheckBox7)
                                        .addComponent(jCheckBox13)
                                        .addComponent(jCheckBox14)
                                        .addComponent(jCheckBox5)
                                        .addComponent(jCheckBox8)
                                        .addComponent(jCheckBox19)
                                        .addComponent(jCheckBox20)
                                        .addComponent(jCheckBox17)
                                        .addComponent(jCheckBox18)
                                        .addComponent(jCheckBox15)
                                        .addComponent(jCheckBox16)
                                        .addComponent(jCheckBox23)
                                        .addComponent(jCheckBox24)
                                        .addComponent(jCheckBox21)
                                        .addComponent(jCheckBox22)
                                        .addComponent(jCheckBox29)
                                        .addComponent(jCheckBox30)
                                        .addComponent(jCheckBox27)
                                        .addComponent(jCheckBox28)
                                        .addComponent(jCheckBox25)
                                        .addComponent(jCheckBox26)
                                        .addComponent(jCheckBox32)
                                        .addComponent(jCheckBox33)
                                        .addComponent(jCheckBox31)
                                        .addComponent(jCheckBox34)
                                        .addComponent(jCheckBox35)
                                        .addComponent(jCheckBox38)
                                        .addComponent(jCheckBox39)
                                        .addComponent(jCheckBox36)
                                        .addComponent(jCheckBox37)
                                        .addComponent(jCheckBox44)
                                        .addComponent(jCheckBox45)
                                        .addComponent(jCheckBox42)
                                        .addComponent(jCheckBox43)
                                        .addComponent(jCheckBox40)
                                        .addComponent(jCheckBox41)
                                        .addComponent(jCheckBox48)
                                        .addComponent(jCheckBox49)
                                        .addComponent(jCheckBox46)
                                        .addComponent(jCheckBox47)
                                        .addComponent(jCheckBox54)
                                        .addComponent(jCheckBox55)
                                        .addComponent(jCheckBox52)
                                        .addComponent(jCheckBox53)
                                        .addComponent(jCheckBox50)
                                        .addComponent(jCheckBox51)
                                        .addComponent(jCheckBox58)
                                        .addComponent(jCheckBox59)
                                        .addComponent(jCheckBox56)
                                        .addComponent(jCheckBox57)
                                        .addComponent(jCheckBox64)
                                        .addComponent(jCheckBox65)
                                        .addComponent(jCheckBox62)
                                        .addComponent(jCheckBox63)
                                        .addComponent(jCheckBox60)
                                        .addComponent(jCheckBox61)
                                        .addComponent(jCheckBox67)
                                        .addComponent(jCheckBox68)
                                        .addComponent(jCheckBox66)
                                        .addComponent(jCheckBox69))
                                .addContainerGap(539, Short.MAX_VALUE))
        );
        cboxPanelLayout.setVerticalGroup(
                cboxPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(cboxPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox4)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox9)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox10)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox11)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox12)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox6)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox5)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox8)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox13)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox14)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox17)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox18)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox19)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox20)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox15)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox16)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox21)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox22)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox23)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox24)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox27)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox28)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox29)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox30)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox25)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox26)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox31)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox32)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox33)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox34)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox35)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox36)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox37)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox38)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox39)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox42)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox43)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox44)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox45)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox40)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox41)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox46)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox47)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox48)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox49)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox52)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox53)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox54)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox55)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox50)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox51)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox56)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox57)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox58)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox59)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox62)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox63)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox64)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox65)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox60)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox61)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox66)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox67)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox68)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox69)
                                .addContainerGap(143, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(cboxPanel);

        phoneNumberLabel.setText("Phone Number:");

        addressLabel.setText("Address:");

        jTextField3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Name:");

        jTextField4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        roofTypeLabel.setText("Roof Type");

        roofTypeBox.setBackground(new Color(51, 255, 255));

        notesLabel.setText("Notes:");

        notesField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                notesFieldActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        GroupLayout jPanelLayout = new GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
                jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 528, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(addButton)
                                                        .addComponent(enterButton)))
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(225, 225, 225)
                                                .addComponent(Title, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(addressLabel, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                                                .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(phoneNumberLabel)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 183, GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(export))
                                                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 567, GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                                .addComponent(notesLabel, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(notesField, GroupLayout.PREFERRED_SIZE, 559, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanelLayout.createSequentialGroup()
                                                                .addComponent(roofTypeLabel, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(roofTypeBox, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 605, GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(642, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
                jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(Title, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(enterButton))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneNumberLabel, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(export))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addressLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(roofTypeLabel, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(roofTypeBox, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(notesField, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(notesLabel, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))
                                .addGap(4442, 4442, 4442))
        );

        Title1.setEditable(false);
        Title1.setBackground(new Color(255, 153, 153));
        Title1.setHorizontalAlignment(JTextField.CENTER);


        jMenu2.setText("File");

        Exit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Q, InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu2.add(Exit);

        roofType.setText("Roof Type");

        metalRoof.setText("Metal Roof");
        metalRoof.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                metalRoofActionPerformed(evt);
            }
        });
        roofType.add(metalRoof);

        shingleRoof.setText("Shingle Roof");
        shingleRoof.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                shingleRoofActionPerformed(evt);
            }
        });
        roofType.add(shingleRoof);

        tileRoof.setText("Tile Roof");
        tileRoof.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                tileRoofActionPerformed(evt);
            }
        });
        roofType.add(tileRoof);

        TPO.setText("TPO");
        TPO.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                TPOActionPerformed(evt);
            }
        });
        roofType.add(TPO);

        polyRoof.setText("Poly Roof");
        polyRoof.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                polyRoofActionPerformed(evt);
            }
        });
        roofType.add(polyRoof);

        builtUp.setText("Built-Up");
        builtUp.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                builtUpActionPerformed(evt);
            }
        });
        roofType.add(builtUp);

        jMenu2.add(roofType);

        inputFile.setText("Choose Excel Input File");
        inputFile.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                inputFileMouseClicked(evt);
            }
        });
        inputFile.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                inputFileActionPerformed(evt);
            }
        });
        jMenu2.add(inputFile);

        exportFile.setText("Choose Export File");
        exportFile.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                exportFileMouseClicked(evt);
            }
        });
        exportFile.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                exportFileActionPerformed(evt);
            }
        });
        jMenu2.add(exportFile);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Title1, GroupLayout.PREFERRED_SIZE, 188, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(470, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(Title1, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();

    }// </editor-fold>

    private void TitleActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void enterButtonActionPerformed(ActionEvent evt) {

        try {

            x.readFile();
            excelRead.ListItems[] xy = x.getArray(jComboBox1.getSelectedItem().toString());
            int numButtons;
            String s1 = jComboBox1.getSelectedItem().toString();
            if (xy == null) {
                numButtons = 1;
            } else
                numButtons = xy.length;
            if (numButtons == 1) {
                for (int i = 1; i < x.items.length; i++) {
                    if (x.items[i].item.contains(s1) || x.items[i].item.equalsIgnoreCase(s1)) {
                        chbox.get(0).setText(x.items[i].item + ": " + x.items[i].description);
                        break;
                    }
                }
            }

            if (numButtons != 1) {
                for (int i = 0; i < numButtons; i++) {
                    chbox.get(i).setText(xy[i].item + ": " + xy[i].description);
                }
            }

            for (int i = 0; i < chbox.size(); i++) {
                chbox.get(i).setVisible(false);
            }

            for (int i = 0; i < numButtons; i++) {
                chbox.get(i).setVisible(true);
            }

            for (int y = 0; y < chbox.size(); y++) {
                if (chbox.get(y).isSelected()) {
                    chbox.get(y).setSelected(false);
                    System.err.println(chbox.get(y).getText());
                }
            }


            cboxPanel.setVisible(true);
            cboxPanel.revalidate();
        } catch (Exception e) {
            System.err.println(e);
        }

    }


    private void jComboBox1ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void cboxPanelMouseWheelMoved(MouseWheelEvent evt) {
        // TODO add your handling code here:

    }

    private void jMenu1ActionPerformed(ActionEvent evt) {
        fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File f = fileChooser.getSelectedFile();
        x.fileName = f.getAbsolutePath();
    }

    private void jCheckBox1ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox9ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addButtonActionPerformed(ActionEvent evt) {
        for (int i = 0; i < chbox.size(); i++) {
            if (chbox.get(i).isSelected()) {
                x.selectedItems.add(chbox.get(i).getText());
            }
        }
    }

    private void jTextField1ActionPerformed(ActionEvent evt) {

    }

    private void notesFieldActionPerformed(ActionEvent evt) {


    }

    private void jMenu1MouseClicked(MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenu1StateChanged(ChangeEvent evt) {
        // TODO add your handling code here:
    }

    private void ExitActionPerformed(ActionEvent evt) {
        System.exit(0);// TODO add your handling code here:
    }

    private void ExitMouseClicked(MouseEvent evt) {
        // TODO add your handling code here:
    }


    private void exportFileMouseClicked(MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void exportFileActionPerformed(ActionEvent evt) {
        fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File f = fileChooser.getSelectedFile();
        x.fileName = f.getAbsolutePath();
    }

    private void inputFileActionPerformed(ActionEvent evt) {

    }

    private void inputFileMouseClicked(MouseEvent evt) {

    }

    private void metalRoofActionPerformed(ActionEvent evt) {
        roofTypeBox.setText("Metal Roof");
        roofTypeBox.revalidate();
    }

    private void tileRoofActionPerformed(ActionEvent evt) {
        roofTypeBox.setText("Tile Roof");
        roofTypeBox.revalidate();
    }

    private void jCheckBox5ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox17ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox21ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox27ActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TPOActionPerformed(ActionEvent evt) {
        roofTypeBox.setText("TPO");
        roofTypeBox.revalidate();
    }

    private void jTextField3ActionPerformed(ActionEvent evt) {

    }

    private void jTextField4ActionPerformed(ActionEvent evt) {


    }

    private void shingleRoofActionPerformed(ActionEvent evt) {
        roofTypeBox.setText("Shingle Roof");
        roofTypeBox.revalidate();
    }

    private void polyRoofActionPerformed(ActionEvent evt) {
        roofTypeBox.setText("Poly Roof");
        roofTypeBox.revalidate();
    }

    private void builtUpActionPerformed(ActionEvent evt) {
        roofTypeBox.setText("Built-Up");
        roofTypeBox.revalidate();
    }

    private void exportActionPerformed(ActionEvent evt) {
        revalidate();
        if (roofTypeBox.getText().isEmpty()) {
            Title1.setText("Choose a Roof Type");
            return;
        } else if (jTextField3.getText().isEmpty()) {
            Title1.setText("Please Enter the Name");
            return;
        } else if (jTextField1.getText().isEmpty()) {
            Title1.setText("Please enter a phone number");
            return;
        } else if (jTextField4.getText().isEmpty()) {
            Title1.setText("Please enter an address");
            return;
        }

        String s3 = jTextField4.getText();
        x.address = s3;
        x.name = jTextField3.getText();
        x._notes = notesField.getText();
        x.roofType = roofTypeBox.getText();
        x.phoneNumber = jTextField1.getText();

        Collections.sort(x.selectedItems);

        for (String s1 : x.selectedItems) {
            System.out.println(s1);
        }
        try {
            x.excelWrite();
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(graphics.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(graphics.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(graphics.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(graphics.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private JMenuItem Exit;
    private JMenuItem TPO;
    private JTextField Title;
    private JLabel addressLabel;
    private JMenuItem builtUp;
    private ButtonGroup buttonGroup1;
    private excelRead x = new excelRead();
    private JPanel cboxPanel;
    private JButton addButton;
    private JButton enterButton;
    private JButton export;
    private JCheckBox jCheckBox1;
    private JCheckBox jCheckBox10;
    private JCheckBox jCheckBox11;
    private JCheckBox jCheckBox12;
    private JCheckBox jCheckBox13;
    private JCheckBox jCheckBox14;
    private JCheckBox jCheckBox15;
    private JCheckBox jCheckBox16;
    private JCheckBox jCheckBox17;
    private JCheckBox jCheckBox18;
    private JCheckBox jCheckBox19;
    private JCheckBox jCheckBox2;
    private JCheckBox jCheckBox20;
    private JCheckBox jCheckBox21;
    private JCheckBox jCheckBox22;
    private JCheckBox jCheckBox23;
    private JCheckBox jCheckBox24;
    private JCheckBox jCheckBox25;
    private JCheckBox jCheckBox26;
    private JCheckBox jCheckBox27;
    private JCheckBox jCheckBox28;
    private JCheckBox jCheckBox29;
    private JCheckBox jCheckBox3;
    private JCheckBox jCheckBox30;
    private JCheckBox jCheckBox31;
    private JCheckBox jCheckBox32;
    private JCheckBox jCheckBox33;
    private JCheckBox jCheckBox34;
    private JCheckBox jCheckBox35;
    private JCheckBox jCheckBox4;
    private JCheckBox jCheckBox5;
    private JCheckBox jCheckBox6;
    private JCheckBox jCheckBox7;
    private JCheckBox jCheckBox8;
    private JCheckBox jCheckBox9;
    private JCheckBox jCheckBox36;
    private JCheckBox jCheckBox37;
    private JCheckBox jCheckBox38;
    private JCheckBox jCheckBox39;
    private JCheckBox jCheckBox40;
    private JCheckBox jCheckBox41;
    private JCheckBox jCheckBox42;
    private JCheckBox jCheckBox43;
    private JCheckBox jCheckBox44;
    private JCheckBox jCheckBox45;
    private JCheckBox jCheckBox46;
    private JCheckBox jCheckBox47;
    private JCheckBox jCheckBox48;
    private JCheckBox jCheckBox49;
    private JCheckBox jCheckBox50;
    private JCheckBox jCheckBox51;
    private JCheckBox jCheckBox52;
    private JCheckBox jCheckBox53;
    private JCheckBox jCheckBox54;
    private JCheckBox jCheckBox55;
    private JCheckBox jCheckBox56;
    private JCheckBox jCheckBox57;
    private JCheckBox jCheckBox58;
    private JCheckBox jCheckBox59;
    private JCheckBox jCheckBox60;
    private JCheckBox jCheckBox61;
    private JCheckBox jCheckBox62;
    private JCheckBox jCheckBox63;
    private JCheckBox jCheckBox64;
    private JCheckBox jCheckBox65;
    private JCheckBox jCheckBox66;
    private JCheckBox jCheckBox67;
    private JCheckBox jCheckBox68;
    private JCheckBox jCheckBox69;

    private JMenuItem exportFile;
    private JMenuItem inputFile;

    private JComboBox<String> jComboBox1;
    private ArrayList<JCheckBox> chbox = new ArrayList<>();

    private JLabel jLabel4;
    private JMenu jMenu1;
    private JMenu jMenu2;
    private JMenu jMenu3;
    private JMenu jMenu4;
    private JMenuBar jMenuBar1;
    private JMenuBar jMenuBar2;
    private JPanel jPanel;
    private JTextField jTextField1;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JMenuItem metalRoof;
    private JTextField notesField;
    private JLabel notesLabel;
    private JLabel phoneNumberLabel;
    private JMenuItem polyRoof;
    private JMenu roofType;
    private JLabel roofTypeBox;
    private JLabel roofTypeLabel;
    private JScrollPane scrollPane;
    private JMenuItem shingleRoof;
    private JMenuItem tileRoof;
    private JFileChooser fileChooser;
    private JTextField Title1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }


    // End of variables declaration
}

